### ISSUE TITLE
let's create an Istanbul community website

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/istanbuljs.github.io#1]
1. the documentation for nyc is becoming Byzantine, it would be nice to have targeted documentation for various approaches to instrumenting your codebase:
  * webpack (CC: @JaKXz).
  * ava (CC: @jamestalmage, @sindresorhus, @novemberborn).
  * babel (_@the-javascript-cool-kids_).
2. it would be nice to have a place to document other important things, e.g., [how do I migrate to Istanbul 1.0?](https://github.com/istanbuljs/nyc/issues/320).

## Proposal

We had great luck with [yargs](https://github.com/yargs/yargs.github.io) using [jekyll](https://jekyllrb.com/) for our static site generation, this still seems to be the best approach.

I'm looping in @lrlna, who lead development on the yargs website; it would be great to have some advice for getting off the ground:

* did you work from any pre-existing templates?
* was there just a generate command that you ran?

## Help Please!

I'm a pretty terrible designer, and probably am not the best person to take point on the visual side of this; I am an alright Ruby developer, so I can help with the Jekyll nitty-gritty.

CC: @gotwarlost, @kentcdodds, @JaKXz, @jamestalmage, @novemberborn

**Comment by kentcdodds** [comment]
Just a tip, this may be too much, but I don't write HTML these days. I build everything with React, even if it's pre-generated and output to an `index.html` file. It makes the code for static sites scale really well. For example: [JavaScriptAir.com](https://javascriptair.com) is all generated from a bunch of React components. It's pretty great.

Though if you wanted to do that, I'd recommend [gatsbyjs](https://github.com/gatsbyjs/gatsby) from @KyleAMathews or [phenomic](https://phenomic.io/) from @MoOx. I haven't really given either of these a super solid look, but I know that Phenomic supports Service Worker to make the static site available offline which would be pretty cool for people looking up docs on an airplane ;-)

**Comment by KyleAMathews** [comment]
I'm hugely biased of course but yeah, using a react.js based static site generator is a really pleasant experience in generally and especially so for JS devs. I'd love to help out if you choose Gatsby! And fwiw, service worker support is coming soonish to Gatsby as well. I'll be working much more now on Gatsby over the next few months and will be whipping things into shape. Yeah for OSS competition! ;-)

**Comment by bcoe** [comment]
@kentcdodds @KyleAMathews definitely willing to give this a shot, if we have some experts willing to pitch in 👍 I'm all for JavaScript continuing to eat the world.

**Comment by KyleAMathews** [comment]
Would be happy to help out. I have a number of documentation sites I need to put together in the nearish future including one for Gatsby + https://github.com/kyleamathews/typography.js so will be thinking/working a lot on this of thing. Something else I'll be adding soon to Gatsby is support for themes where the hope is all these doc sites could be using a shared "theme" which is simply an NPM module that you install and start adding content to.

Also I'm in SF and I see @bcoe you're in Oakland so if you ever want to host a hack day I could show up easily enough :-)

**Comment by MoOx** [comment]
Thanks @kentcdodds for poking me.

As the creator of Phenomic, I am also hugely biased :)

I would recommand you taking a look to an entry on Phenomic FAQ that try to list majors differences between Phenomic and Gatsby https://phenomic.io/docs/faq/gatsby/ (not reviewed by @KyleAMathews yet even if I poked him - he is probably busy)

Here are some key points I would like to highlight:

- like gatsby, Phenomic generate HTML for all pages (so works without JS)
- unlike gatsby, Phenomic does not put all content of the website in the JS client side bundle (content is loaded on demand only, which is a must have for moderate and big websites)
- offline support can be enabled with a single boolean flag to save all content of the website (make sense for docs) but you have plenty of options in case you want something more flexible (like cache when viewed) https://phenomic.io/docs/advanced/offline-browsing/
- we will offer soon a built-in search probably via algolia, but I will try to offer alternatives (note that it can already be setup pretty easily - some of our users already did this with just a few lines of code)
- a plugin system is coming soon so you can tweak the content consumed by phenomic
- themes will be a thing too ;)
- in case you have some questions before making your choices, here is a link to our gitter chat https://gitter.im/MoOx/phenomic

Phenomic is not meant to be a closed/magic box: you have full control over any step of the build process. And you also have full control over your webpack and babel config etc. We offer flexibility for built-in options via JSON or CLI args (we use yargs and an additional custom layer to validates all options and values so you make any mistakes).

Btw, Phenomic offers by default best practices with eslint/stylelint and uses under the hood AVA for its tests.

I would be very happy and proud that istanbul community take a look to [Phenomic](http://phenomic.io/) (like [some others communities and OSS projects](https://phenomic.io/showcase/)) and give us a feedback about the UX/DX as I am a huge fan of nyc (obviously used for Phenomic coverage and all my recent projects that are covered by tests - which means all my recent projects haha).

**Comment by bcoe** [comment]
@MoOx, @KyleAMathews, @kentcdodds, I'm going to do my best King Solomon impersonation here; would love to find a way for us to all work together. If there are many helping hands, I have no objection to pulling in either technology -- any thoughts about how we could find some common ground?

Perhaps we could start by brainstorming some of the sections we'd like to see in an Istanbul/nyc website?

**Comment by lrlna** [comment]
👋 ! I built the yargs website with just html, sass, and jekyll; no templates, no generators. It was a pretty simple one, so I didn't think using react components etc. was necessary. We are, however, using [flatdoc](https://github.com/rstacruz/flatdoc) to get our docs from the readme. Would be totally cool to explore other tools with this one, I think! 


_@bcoe, 😂 😂 at King Solomon impersonation_, I agree though ✨

**Comment by kentcdodds** [comment]
One such tool you might consider is [doclets.io](https://doclets.io/) which I've tried on two projects and was fairly impressed. Though I think it's more centered around documenting functions with JSDoc rather than a CLI and package.json config...

**Comment by gotwarlost** [comment]
I'll opt out on all discussions of website generators and UX design issues :) I'm terrible at this stuff.

**Comment by gotwarlost** [comment]
That said, I've been writing the JSDocs for the libraries, assuming that `documentation` would be the tool to generate it.

**Comment by bcoe** [comment]
<img width="1239" alt="screen shot 2016-08-02 at 1 34 46 pm" src="https://cloud.githubusercontent.com/assets/194609/17344175/16c7166a-58b6-11e6-8e5f-64092ef7f3a4.png">

@gotwarlost I had a couple days off, and hammered out the skeleton of a website using yargs as a starting point -- will have a pull request we can argue about later tonight hopefully.

**Comment by davglass** [comment]
@bcoe Nice!

**Comment by JaKXz** [comment]
When there's an FAQ section in place, the first PR to make would say something about how the Istanbul name now _[only]_ refers to all the underlying libraries that produce the coverage and reports and so on. That was / can be a point of confusion so the wording that says nyc is "Istanbul's CLI..." is 👍 

re: webpack - we're still looking for way to resolve webpack's importing magic with nyc's instrumentation. "Smaller" (read: less complex) projects that don't use things like webpack's resolve root plugins whose tests are very simple node modules will work fine as is, but for things like `karma-webpack` I still am without a solution unfortunately. If someone has it working please do make a PR with a recipe to nyc's docs!

**Comment by gotwarlost** [comment]
@bcoe - looks great. Please go ahead and publish when you think it's ready. I've gone into head-up-ass mode again and don't want to be a blocker for any of this.
