### ISSUE TITLE
Site not found

### ISSUE THREAD

**Issue by munierujp** [istanbuljs/istanbuljs.github.io#155]
https://istanbul.js.org/

<img width="839" alt="スクリーンショット 2020-12-11 9 15 10" src="https://user-images.githubusercontent.com/20086673/101845188-696d4e80-3b91-11eb-9b2c-eb0071dd47cb.png">

**Comment by coreyfarrell** [comment]
Thank you for the report, I'm looking into this issue but have not yet found resolution.  For now you can still access the documentation site via https://istanbuljs.github.io/.  I will comment again and close this issue when istanbul.js.org is working again.

**Comment by 7rulnik** [comment]
@coreyfarrell maybe we can temporarily replace links to documentation in repo description?
![image](https://user-images.githubusercontent.com/5969049/102376199-6da3cc80-3fd4-11eb-8792-63dd5d67b4c3.png)

**Comment by coreyfarrell** [comment]
istanbul.js.org is fixed.
