### ISSUE TITLE
Your use of SRC directory is quite confusing..

### ISSUE THREAD

**Issue by yvele** [istanbuljs/istanbuljs.github.io#22]
..isn't it?

That's not a standard but most of open source projects using transpilation (with BabelJS) are using both `src`and `lib`directories :
- `src` is used for original ES2015 code (before transpilation, under SCM)
- `lib` is used for distribued ES5 code (after transpilation, distribued within NPM package, excluded from SCM)

(see BabelJS itself : https://github.com/babel/babel/tree/master/packages/babel-core/src)

In your ES2015 tutorials ([prerequisites](https://github.com/istanbuljs/istanbuljs.github.io/blob/development/content/docs/tutorials/es2015.md#prerequisites) and [shipping](https://github.com/istanbuljs/istanbuljs.github.io/blob/development/content/docs/tutorials/es2015.md#shipping-your-code)) you are using `src` as the distribution directory, and that really confusing.. Here:
- https://github.com/istanbuljs/istanbuljs.github.io/blame/development/content/docs/tutorials/es2015.md#L126-L141
- https://github.com/istanbuljs/istanbuljs.github.io/blame/development/content/docs/tutorials/es2015.md#L87-L95

**Comment by bcoe** [comment]
@MoOx perhaps you can speak to this convention?

**Comment by MoOx** [comment]
I usually use

```js
    "transpile": "babel --ignore __tests__ --copy-files src --out-dir lib",
```

**Comment by JaKXz** [comment]
I'm going to close this for now since it's more of a phenomic issue.
