### ISSUE TITLE
security certificate expired 

### ISSUE THREAD

**Issue by egoroof** [istanbuljs/istanbuljs.github.io#26]
![screenshot 2017-02-13 22 42 33](https://cloud.githubusercontent.com/assets/2605831/22890105/e9431d3e-f23d-11e6-972f-142b4b6c3571.png)

> Subject: sni103429.cloudflaressl.com
> Issuer: COMODO ECC Domain Validation Secure Server CA 2
> Expires on: Feb 13, 2017
> Current date: Feb 13, 2017

**Comment by novemberborn** [comment]
Yikes! I think https://github.com/js-org/js.org/issues/14 is the appropriate discussion thread for this (this isn't something the istanbuljs organization has any control over). Thanks for reporting this.
