### ISSUE TITLE
write content for AVA tutorial

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/istanbuljs.github.io#5]
There's a section in the new website just itching for some AVA specific tutorial content:

http://istanbul.js.org/2016/08/02/ava.html

Would love your help filling it in, CC: @jamestalmage, @novemberborn, @sindresorhus

**Comment by JaKXz** [comment]
I think AVA already has a recipe for coverage in its docs, we should probably just link to it.

**Comment by bcoe** [comment]
@jamestalmage @novemberborn @sindresorhus feel free to submit any edits you'd like to see made:

http://istanbul.js.org/docs/tutorials/ava/
