### ISSUE TITLE
write content for node-tap tutorial

### ISSUE THREAD

**Issue by bcoe** [istanbuljs/istanbuljs.github.io#9]
there's a section waiting to call out node-tap's coverage support, I know it basically works just out of the gate ... but I think it would be neat to show this off to people:

http://istanbul.js.org/2016/08/02/tap.html

CC: @isaacs

**Comment by isaacs** [comment]
This page is probably relevant: http://www.node-tap.org/coverage/

**Comment by bcoe** [comment]
@isaacs feel free to submit any edits you'd like to see made:

http://istanbul.js.org/docs/tutorials/tap/
